/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.s.jmotors.Staff;

import com.mycompany.s.jmotors.VehicleOwner.VehicleOwnerHome;
import com.toedter.calendar.JCalendar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdul Rehman Sodais
 */
public class AddAttendance extends javax.swing.JFrame {

    static String ID;
    static String Name;
    static String Username;
    static String Phoneno;
    static String Password;
    static String Type;
    static String FManagerID;
    static String outletID;
    
    /**
     * Creates new form AddAttendance
     */
      Staff s;
    Connection addattendance;
    
    public AddAttendance() 
    {
        initComponents();
        
        setExtendedState(AddAttendance.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Today's Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 210, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mark Present");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 230, 50));

        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 250, 170));

        jPanel2.setBackground(new java.awt.Color(241, 202, 186));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mark Attendance");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 780, 70));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 1230, 490));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\theharism\\Desktop\\S-JMotors\\hL1kMq (8).jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
        StaffControls s3 = new StaffControls();
        s3.staffcontrolcon(addattendance);
         s3.setVisible(true);
       setVisible(false);
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       SimpleDateFormat f = new SimpleDateFormat();
       Date d1 = null;
       
       try
       {
           d1 = f.parse(f.format(jCalendar1.getDate()));
         //JOptionPane.showMessageDialog(null, f.format(d1));
         JOptionPane.showMessageDialog(null, "Attendance Marked");
       }
       
       catch(Exception E)
       {
           
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setUsername(String username)
    {
        String query = "SELECT ID,Name,Username,Phoneno,outletID,Password,Type,FManagerID FROM Staff WHERE username = ?";
        
        PreparedStatement pdt;
          try {
                pdt = addattendance.prepareStatement(query);
                pdt.setString(1,username);
                
                ResultSet rs = pdt.executeQuery();
                 
                while(rs.next())
                {
                    ID = rs.getString("id");
                    Name = rs.getString("name");
                    Username = rs.getString("username");
                    Phoneno = rs.getString("phoneno");
                    Password = rs.getString("password");
                    Type = rs.getString("Type");
                    outletID = rs.getString("outletID");  
                    FManagerID = rs.getString("FManagerID");
                }
                
                s = new Staff();
                s.AddStaff(ID, FManagerID, Name, username, Password, Phoneno, outletID, Type);
                
          } catch (SQLException ex) {
            Logger.getLogger(VehicleOwnerHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String query2="INSERT INTO Attendance VALUES(?,?,?)";
        SimpleDateFormat f = new SimpleDateFormat();
       Date d1 = null;
       
        try {
            d1 = f.parse(f.format(jCalendar1.getDate()));
        } catch (ParseException ex) {
            Logger.getLogger(AddAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PreparedStatement pdt;
          
        try
        {
            
            pdt = addattendance.prepareStatement(query2);
             
                 
                 pdt.setString(1,s.ID );
                 pdt.setString(2,f.format(d1));
                 pdt.setString(3,"P");
                 pdt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated  successfully");
            
        } catch (SQLException ex) {
            
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

     public void addattendancecon (Connection con)
    {
        this.addattendance = con;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
